MOCK_PRODUCTS = [
    {
        "id": "amz-echo-dot-5",
        "title": "Echo Dot (5th Gen) Smart Speaker",
        "brand": "Amazon",
        "price": 49.99,
        "currency": "USD",
        "retailer": "Amazon",
        "url": "https://www.amazon.com/",
        "images": ["https://placehold.co/600x400?text=Echo+Dot"],
        "rating": 4.6,
        "availability": "in_stock",
    },
    {
        "id": "bb-soundbar-200",
        "title": "Cinematic Soundbar 2.1",
        "brand": "BestBuy",
        "price": 199.99,
        "currency": "USD",
        "retailer": "BestBuy",
        "url": "https://www.bestbuy.com/",
        "images": ["https://placehold.co/600x400?text=Soundbar"],
        "rating": 4.4,
        "availability": "in_stock",
    },
    {
        "id": "wm-robot-vac-300",
        "title": "Robot Vacuum Pro 3000",
        "brand": "Walmart",
        "price": 279.0,
        "currency": "USD",
        "retailer": "Walmart",
        "url": "https://www.walmart.com/",
        "images": ["https://placehold.co/600x400?text=Robot+Vacuum"],
        "rating": 4.2,
        "availability": "in_stock",
    },
    {
        "id": "tg-airfryer-7l",
        "title": "Air Fryer XL 7L",
        "brand": "Target",
        "price": 119.0,
        "currency": "USD",
        "retailer": "Target",
        "url": "https://www.target.com/",
        "images": ["https://placehold.co/600x400?text=Air+Fryer"],
        "rating": 4.5,
        "availability": "in_stock",
    },
    {
        "id": "as-kindle-paper",
        "title": "Kindle Paperwhite 6.8",
        "brand": "Amazon",
        "price": 139.99,
        "currency": "USD",
        "retailer": "Amazon",
        "url": "https://www.amazon.com/",
        "images": ["https://placehold.co/600x400?text=Kindle"],
        "rating": 4.7,
        "availability": "in_stock",
    },
]
